### ISSUE TITLE
CI: Look that scripts without ending are included in build artifact

### ISSUE THREAD

**Issue by BacLuc** [scs/jumpstart-docs#16]
The scripts in the linux exercise are not included in the build artifact.

**Comment by BacLuc** [comment]
In Build https://github.com/scs/jumpstart-docs/actions/runs/1118983351,
the code snippets of the linux folder were available.
In https://github.com/scs/jumpstart-docs/actions/runs/1303821451 not anymore

**Comment by langchr86** [comment]
This is fixed here: https://github.com/scs/jumpstart-docs/commit/267ec339ca1c40d4795188acfffda222e6b1bc01
