### ISSUE TITLE
CI/CD Github Actions durch Jenkins oder Bitbucket Pipelines ersetzten?

### ISSUE THREAD

**Issue by langchr86** [scs/jumpstart-docs#56]
Damit die Praxisnähe verbessert wird und die Einstiegshürde, um dies in der SCS zu nutzen, sinkt.

Zuerst mal abwarten, bis BB Pipelines in der SCS eingeführt wurde.

**Comment by Nitschi** [comment]
+1 für Bitbucket Pipelines

**Comment by langchr86** [comment]
Bitbucket selber hat keine interaktiven Tutorials. Man könnte aber auf der Doku basieren: https://support.atlassian.com/bitbucket-cloud/docs/get-started-with-bitbucket-pipelines/

Ein Tutorial das evtl. verwendet werden könnte wäre https://chrisfrew.in/blog/mastering-bitbucket-pipelines-for-ci-and-cd/ . Man müsste aber da noch Dinge vorbereiten.

Folgende Anleitung könnte als Ergänzung referenziert werden: https://hevodata.com/learn/bitbucket-pipelines/

**Comment by langchr86** [comment]
Wurde im Feedback 2023-10 zweimal gewünscht.

**Comment by langchr86** [comment]
Eine Variante wäre auch, das Tutorial von github zu "kopieren" und auch Bitbucket anzupassen.

**Comment by anitsch-scs** [comment]
Da das CI/CD Kapitel ja rein inhaltlich gut durchdacht ist, würde ich eine Anpassung an Bitbucket Pipelines vorschlagen.
Evtl. noch kleine Info/Übung, dass auch ein einfacher Usecase mit Artifactory dabei ist.
