### ISSUE TITLE
Neues Modul für SW Konzepte?

### ISSUE THREAD

**Issue by langchr86** [scs/jumpstart-docs#65]
Brauchen wir evtl. ein neues Module für grundlegende SW Konzepte wie:

* Dependency Injection
* Dependency Inversion Principle
* die wichtigsten Patterns (Observer, Factory, etc.)
* UML (Klassen und Sequenz)
* evtl. weitere Themen für Architektur/Design
* Wartbarkeit und Testbarkeit

**Comment by Nitschi** [comment]
Auszug aus einer Email an Jérôme:


Anbei eine Ideensammlung, was man als Jumpstart Clean-Coders den Mitarbeitern (v.a. direkt von der Uni) beibringen könnte:
-	SOLID Principles (Buch: Clean-Code)
  o	Single Responsibility
  o	Open-Closed
  o	(L I)
  o	Dependency Inversion Principle
-	Qualitätskriterien
  o	Erweiterbarkeit
  o	Lesbarkeit
  o	Testbarkeit
  o	Reproduzierbarkeit
-	Professionalism (Buch: Software Craftsmanship & The Clean Coder & [clean-coders blog](https://blog.cleancoder.com/uncle-bob/2013/02/10/ThePrinciplesOfCraftsmanship.html))
  o	Kontinuierlich Mehrwert schaffen
  o	Ehrlichkeit, Bescheidenheit, Hilfsbereitschaft und Proaktivität
  o	Für Qualität einstehen
  o	Wohlüberlegte Zeitschätzungen (nicht unter Druck ändern, nur bei neuen Informationen oder Scope Änderung)
  o	Selbstständige Weiterbildung
-	Design Patterns (https://refactoring.guru/design-patterns & Head first Design Patterns)
  o	Observer
  o	Factory
  o	Dependency Injection
  o	Strategy
  o	Wann man sie (nicht) einsetzen sollte
-	Best Practices
  o	Code Review (https://www.youtube.com/watch?v=a9_0UUUNt-Y)
  o	Continuous Integration
  o	Dokumentation
  o	Infrastructure/Dev Setup as Code

**Comment by langchr86** [comment]
Folgendes Online-Buch könnte als Basis/Referenz dienen: https://refactoring.guru/design-patterns

**Comment by langchr86** [comment]
Unabhängige Meldungen im Feedback der Jumpstart-Durchführung 2023-10:
* Evtl. wäre ein ganzer Block über Sprach-unabhängige Konzepte im Stile von "Design-Patterns" "functional vs. OOP" interessant. 
* Vorschlag: Clean Coders Input
